#!/bin/bash
# =============================================================================
# Atlas Server — Automated Setup Script
# =============================================================================
# Automates hardening and Docker setup for Ubuntu 24.04 LTS
# Run as root on a fresh server: sudo bash setup.sh
#
# IMPORTANT: Review and adjust the variables below before running!
# =============================================================================

set -euo pipefail

# ─── Configuration ──────────────────────────────────────────────────────────
ADMIN_USER="admin"
SSH_PORT="22222"
TIMEZONE="Europe/Zurich"

# Docker network name for reverse proxy communication
DOCKER_NETWORK="proxy"

# Service directories to create under /opt/docker/
SERVICES=(npm heimdall uptimekuma nextcloud paperless stirlingpdf whoogle vaultwarden)

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# ─── Helper Functions ───────────────────────────────────────────────────────
log()  { echo -e "${GREEN}[✓]${NC} $1"; }
warn() { echo -e "${YELLOW}[!]${NC} $1"; }
info() { echo -e "${BLUE}[i]${NC} $1"; }
fail() { echo -e "${RED}[✗]${NC} $1"; exit 1; }

check_root() {
    if [[ $EUID -ne 0 ]]; then
        fail "This script must be run as root (sudo bash setup.sh)"
    fi
}

confirm() {
    read -rp "$(echo -e "${YELLOW}[?]${NC} $1 [y/N]: ")" response
    [[ "$response" =~ ^[yY]$ ]]
}

# ─── Phase 1: System Basics ────────────────────────────────────────────────
setup_system() {
    info "Updating system packages..."
    apt update && apt upgrade -y
    apt install -y curl wget git nano ufw fail2ban unattended-upgrades

    info "Setting timezone to ${TIMEZONE}..."
    timedatectl set-timezone "$TIMEZONE"

    log "System packages updated and timezone set"
}

# ─── Phase 2: Admin User ───────────────────────────────────────────────────
setup_user() {
    if id "$ADMIN_USER" &>/dev/null; then
        warn "User '${ADMIN_USER}' already exists, skipping creation"
    else
        info "Creating admin user '${ADMIN_USER}'..."
        adduser --gecos "" "$ADMIN_USER"
        usermod -aG sudo "$ADMIN_USER"
        log "User '${ADMIN_USER}' created and added to sudo group"
    fi

    # Setup SSH directory for admin user
    ADMIN_HOME="/home/${ADMIN_USER}"
    SSH_DIR="${ADMIN_HOME}/.ssh"
    mkdir -p "$SSH_DIR"

    if [[ -f /root/.ssh/authorized_keys ]]; then
        info "Copying root's authorized_keys to ${ADMIN_USER}..."
        cp /root/.ssh/authorized_keys "${SSH_DIR}/authorized_keys"
    fi

    # Set correct permissions (critical for SSH key auth)
    chmod 750 "$ADMIN_HOME"
    chmod 700 "$SSH_DIR"
    chmod 600 "${SSH_DIR}/authorized_keys" 2>/dev/null || true
    chown -R "${ADMIN_USER}:${ADMIN_USER}" "$SSH_DIR"

    log "SSH directory configured with correct permissions"
}

# ─── Phase 3: SSH Hardening ─────────────────────────────────────────────────
harden_ssh() {
    info "Hardening SSH configuration..."

    # Backup original config
    cp /etc/ssh/sshd_config /etc/ssh/sshd_config.bak

    cat > /etc/ssh/sshd_config.d/99-hardening.conf << EOF
# Atlas Server — SSH Hardening
# Generated by setup.sh

Port ${SSH_PORT}
PermitRootLogin no
PasswordAuthentication no
PubkeyAuthentication yes
MaxAuthTries 3
LoginGraceTime 30
AllowUsers ${ADMIN_USER}
X11Forwarding no
ClientAliveInterval 300
ClientAliveCountMax 2
EOF

    # Validate config before applying
    if sshd -t; then
        systemctl restart sshd
        log "SSH hardened: Port ${SSH_PORT}, key-only, root disabled"
    else
        fail "SSH config validation failed! Check /etc/ssh/sshd_config.d/99-hardening.conf"
    fi

    warn "IMPORTANT: Test SSH login in a NEW terminal before closing this session!"
    warn "Command: ssh -p ${SSH_PORT} ${ADMIN_USER}@<SERVER_IP>"
}

# ─── Phase 4: Firewall ─────────────────────────────────────────────────────
setup_firewall() {
    info "Configuring UFW firewall..."

    ufw default deny incoming
    ufw default allow outgoing

    ufw allow "${SSH_PORT}/tcp" comment 'SSH'
    ufw allow 80/tcp comment 'HTTP - NPM'
    ufw allow 443/tcp comment 'HTTPS - NPM'

    echo "y" | ufw enable

    log "UFW active — open ports: ${SSH_PORT}, 80, 443"
    ufw status numbered
}

# ─── Phase 5: Fail2Ban ──────────────────────────────────────────────────────
setup_fail2ban() {
    info "Configuring Fail2Ban..."

    cat > /etc/fail2ban/jail.local << EOF
[sshd]
enabled = true
port = ${SSH_PORT}
maxretry = 3
findtime = 600
bantime = 3600
banaction = ufw
EOF

    systemctl enable fail2ban
    systemctl restart fail2ban

    log "Fail2Ban active: 3 retries → 1 hour ban via UFW"
}

# ─── Phase 6: Kernel Hardening ──────────────────────────────────────────────
harden_kernel() {
    info "Applying kernel hardening via sysctl..."

    cat > /etc/sysctl.d/99-hardening.conf << EOF
# Atlas Server — Kernel Hardening

# IP Spoofing prevention
net.ipv4.conf.all.rp_filter = 1
net.ipv4.conf.default.rp_filter = 1

# ICMP Redirects (MITM protection)
net.ipv4.conf.all.accept_redirects = 0
net.ipv4.conf.default.accept_redirects = 0
net.ipv4.conf.all.send_redirects = 0

# SYN Flood protection
net.ipv4.tcp_syncookies = 1

# Source Routing disabled
net.ipv4.conf.all.accept_source_route = 0

# Log suspicious packets (Martians)
net.ipv4.conf.all.log_martians = 1
net.ipv4.conf.default.log_martians = 1

# Disable IPv6
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
EOF

    sysctl -p /etc/sysctl.d/99-hardening.conf

    log "Kernel hardening applied"
}

# ─── Phase 7: Shared Memory ────────────────────────────────────────────────
secure_shm() {
    info "Securing shared memory..."

    if ! grep -q "/run/shm" /etc/fstab; then
        echo "tmpfs /run/shm tmpfs defaults,noexec,nosuid 0 0" >> /etc/fstab
        log "Shared memory secured (noexec, nosuid)"
    else
        warn "Shared memory entry already exists in /etc/fstab"
    fi
}

# ─── Phase 8: Auto Updates ─────────────────────────────────────────────────
setup_auto_updates() {
    info "Enabling automatic security updates..."

    dpkg-reconfigure -plow unattended-upgrades

    log "Unattended upgrades enabled"
}

# ─── Phase 9: Disable Unnecessary Services ──────────────────────────────────
disable_services() {
    info "Disabling unnecessary services..."

    for svc in snapd cups; do
        if systemctl is-active --quiet "$svc" 2>/dev/null; then
            systemctl disable --now "$svc"
            log "Disabled: ${svc}"
        fi
    done
}

# ─── Phase 10: Docker Installation ─────────────────────────────────────────
install_docker() {
    if command -v docker &>/dev/null; then
        warn "Docker already installed, skipping"
    else
        info "Installing Docker..."

        curl -fsSL https://get.docker.com | sh
        usermod -aG docker "$ADMIN_USER"

        systemctl enable docker
        systemctl start docker

        log "Docker installed and ${ADMIN_USER} added to docker group"
    fi
}

# ─── Phase 11: Docker Network & Directories ────────────────────────────────
setup_docker_env() {
    info "Creating Docker network '${DOCKER_NETWORK}'..."

    if docker network inspect "$DOCKER_NETWORK" &>/dev/null; then
        warn "Network '${DOCKER_NETWORK}' already exists"
    else
        docker network create "$DOCKER_NETWORK"
        log "Docker network '${DOCKER_NETWORK}' created"
    fi

    info "Creating service directories under /opt/docker/..."
    for svc in "${SERVICES[@]}"; do
        mkdir -p "/opt/docker/${svc}"
    done
    chown -R "${ADMIN_USER}:${ADMIN_USER}" /opt/docker

    log "Directory structure created"
}

# ─── Main ───────────────────────────────────────────────────────────────────
main() {
    echo ""
    echo "========================================"
    echo "  Atlas Server — Automated Setup"
    echo "  Ubuntu 24.04 LTS"
    echo "========================================"
    echo ""

    check_root

    warn "This script will:"
    echo "  1.  Update system packages"
    echo "  2.  Create admin user '${ADMIN_USER}'"
    echo "  3.  Harden SSH (port ${SSH_PORT}, key-only, no root)"
    echo "  4.  Configure UFW firewall (3 ports)"
    echo "  5.  Setup Fail2Ban"
    echo "  6.  Apply kernel hardening"
    echo "  7.  Secure shared memory"
    echo "  8.  Enable auto updates"
    echo "  9.  Disable unnecessary services"
    echo "  10. Install Docker + Docker Compose"
    echo "  11. Create Docker network + directories"
    echo ""

    if ! confirm "Proceed with setup?"; then
        echo "Aborted."
        exit 0
    fi

    setup_system
    setup_user
    harden_ssh
    setup_firewall
    setup_fail2ban
    harden_kernel
    secure_shm
    setup_auto_updates
    disable_services
    install_docker
    setup_docker_env

    echo ""
    echo "========================================"
    echo -e "${GREEN}  Setup complete!${NC}"
    echo "========================================"
    echo ""
    echo "  Next steps:"
    echo "  1. Test SSH in a NEW terminal:"
    echo "     ssh -p ${SSH_PORT} ${ADMIN_USER}@<SERVER_IP>"
    echo ""
    echo "  2. Deploy services from /opt/docker/"
    echo "     cd /opt/docker/npm && docker compose up -d"
    echo ""
    echo "  3. DO NOT close this session until SSH is verified!"
    echo ""
}

main "$@"
